apiVersion: apps/v1
kind: Deployment
metadata:
  name:  stock-sell-inference
spec:
  selector:
    matchLabels:
      app: stock-sell-inference
  replicas: 1
  template:
    metadata:
      labels:
        app:  stock-sell-inference
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  inference
        image:  anuroop21/stock-sell-api:metrics
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: SELL_THRESHOLD  # Because, FastAPI expects this variable to be present
          value: "0.7"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 512m
            memory: 500Mi